language: python
python:
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: kkremitzki
  password:
    secure: aYcPDhhR8e7w/vPMRCdU7QVgFofk9qsn+eL4GkkIwx2tSzL+8ST8JQbb2mDT8QRvJB6h05OTigGKLEnycCqBF/QH6pwmsg70jA7mjoieoB0qzsHAEVF0E7ovbDTzBaMxJiHUL37LmHbaZQ5dLbvOwIxn2fZ/iedVm/zgTorK4Q/4grQ7GKR+pdxvg4zrUq587dI8wMxKuZb5i/5y5AlkR7AvjPa+h63JkTBLP8tm1tqWGpbntUFf3WRpb4T6rBoaBgHS7epCqvG3E32MsY6lvOGS3RmeB2WyPbZk6Gb9J+KzczHxYs7gRi01QEEZOVsA2saC6w2yu+vKS0rIW0urGkcBYxfbNrNykjk7qstMhs+u+hd7Wx7RzxcUhpljfwchvGCHdrYc5RtJ/XpFizaOAtphfIF11DDnZy79NMnXy6Ww5nLyg+tEQvUhDwQdKHrGjaS53ZIRchGn+tekiZ+k3dy4LSy/2ww7ONtkbwKZr+Fsu03FGOoSmp/OiFQQydcqhK3Ea3Ha26hH9t22UAn6cdGiOL6SDM7jz7GkN8E+2hQoU9bDPySEhn09nHNawtHlaKxUXv430+Ohkyyt8rzmMReJ0EkaiIK5jjPSKtTUOHHLgfCP4IH2fkS2aIHBbPDlhXLNStt+/bgndLwZUws1OjMgH4jtY0G2Ch1/S4G/fqw=
  on:
    tags: true
    repo: kkremitzki/kremitzki_python_experiments
    python: 3.6
