language: python
python:
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: kkremitzki
  password:
    secure: N4N8nZr15Da3o6g/N6PGwT7IaYkBHIVxZsZrF+eZW9EIn5dvLP9psWGQqpiiXpCEGmLKx9r+y/vKZRTZSVlK4z3bdWSq5m2TnjsKF2cGq3SdNgE4WPNncCEMewbnEFqioUOh2TK5sHivIRU4EvqTNX5y7rIG+U9iHwjLQX1IlGH2DFjImLuYuWhIf40ZcMphFgXkoMXYg+NYQqdVu/KgT4qj4VCpV+QRIISDxERe1QtfvPUbIziAGY1gR9/aM2ETcSZ8L6x+iEUQQRbtvEr5MKeFburExIY0cvpIPX1z+vmulkgh3caP/oEW5JbY+X25vT39udYpGL/XWWXkkf7Nq0XyXnvmS3FX7ctJWxrV132Cnp6OM1SHD4QIwbWvv++b8etwnH0D+k5zf9UG+H/LpNgMMHbMPGzMd4kVHwnlUBs89eWwA+Cxs7pWk7smsB9PB+Fv7xYggTT/c7gdGbDapF7oeRozDZycA/x61LBc5p1DXFIN2U3cdiSgDV7aRtz8Kh2dqRtPv+L8nQecw9nojOXGa0cVsoNXwWyqfYjnHkCym7Kekqn12DWf2sPseZVraT1NVK/NadrgeX57wW8UAeI+mZv7Ckh1J59HCo1Qh9xMwa01G6c978vTDZWjXwPnZvVQMIUjsc9Hp0fLijwXOw+ww1xKOa2Az2QXRCfOCa0=
  on:
    tags: true
    repo: kkremitzki/kremitzki_python_experiments
    python: 3.6
